config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show] 
  resources :comments, only: [:index, :new, :create, :edit, :update, :destroy, :show] 
  
  devise_for :users, :controllers => { registrations: "users/registrations", 
  sessions: "users/sessions" }
  delete "users/delete_account", to: "users/registrations#delete_account", as: :delete_account_user
  #devise_scope :user do   
  #end
  
  #resources :users, only: [:destroy]
  
  resources :events
  get '/update_year', to: 'events#update_year'
 
  root "home#index"
  get "events", to: "events#calendar"
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  post "contact", to: "pages#contact"
  #get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #get "posts#index"
  #get "comments#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @crops = Crop.all
    @recent_posts = Post.order(created_at: :desc).limit(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container mt-5">

  <h2>Crop Calendar <%= Time.current.year %></h2>
  <div class="table-responsive mt-3 mb-3">
  <table class="table table-striped table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th>crop</th>
        <% Date::MONTHNAMES.drop(1).each do |month| %>
          <th><%= month %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @crops.each do |crop| %>
        <tr>
          <td><%= crop.name %></td>
          <% (1..12).each do |month| %>
            <td>
            
              <% if crop.planting_months.include?(month.to_s) %>
               <span class="planting">Plant</span>
              <% elsif crop.harvest_months.include?(month.to_s) %>
               <span class="harvest">Harvest</span>
              <% elsif crop.mid_season_months.include?(month.to_s) %>
               <span class="mid-season">Mid</span>
              <% end %>
              
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <p><a href="/events">Average Monthly Precipitation By BMKG</a></p>
  
  <div class="row mb-4">
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">Forum</h5>
          <p class="card-text">Discuss Topics And Share Ideas.</p>
        </div>
        <div class="card-footer text-center">
          <%= link_to 'View Posts', posts_path, class: 'btn btn-primary me-2' %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary me-2' %>
        
          <% if user_signed_in? %>
            <%= button_to 'Delete My Account', user_registration_path, method: :delete, data: { confirm: 'Are you sure you want to delete your account? This action cannot be undone.' } %>
            <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">Recent Posts</h5>
          <p class="card-text">Check out our latest posts:</p>
          <ul class="list-unstyled">
            <% @recent_posts.each do |post| %>
              <li>
                <%= link_to post.title, post_path(post) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
    
  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">About</h5>
          <p class="card-text">Purpose Of The Application.</p>
        </div>
        <div class="card-footer text-center">
          <%= link_to 'About', about_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">Contact</h5>
          <p class="card-text">If you have any questions, feel free to reach out!.</p>
        </div>
        <div class="card-footer text-center">
          <%= link_to 'Contact Us', contact_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>