config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show] 
  resources :comments, only: [:index, :new, :create, :edit, :update, :destroy, :show] 
  
  devise_for :users, :controllers => { registrations: "users/registrations", 
  sessions: "users/sessions" }
  delete "users/delete_account", to: "users/registrations#delete_account", as: :delete_account_user
  #devise_scope :user do   
  #end
  
  #resources :users, only: [:destroy]
  
  resources :events
  get '/update_year', to: 'events#update_year'
 
  root "home#index"
  get "events", to: "events#calendar"
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  post "contact", to: "pages#contact"
  #get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #get "posts#index"
  #get "comments#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  before_destroy :delete_associated_comments
  validates :title, :body, presence: true

  private

  def delete_associated_comments
    comments.destroy_all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_post_owner, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show 
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post.id).includes(:user) 
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit 
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!
    respond_to do |format|
      #if @post.user == current_user
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
      #else
        #format.html { redirect_to @post, alert: 'You are not authorized to delete this post.' }
        #format.json { render json: { error: 'Unauthorized' }, status: :forbidden }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def check_post_owner
    redirect_to posts_path, alert: 'You are not authorized to perform this action.' unless @post.user == current_user
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit "Save Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="card edit-post-card my-5">
  <div class="card-body-edit">
    <h1 class="edit-post-title text-center">Edit Post</h1>

    <%= form_with(model: @post, local: true) do |form| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this content from being saved:</h2>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= form.label :body, class: "form-label" %>
        <%= form.text_area :body, class: "form-control" %>
      </div>
    
      <div class="text-center">
        <%= form.submit 'Update Post' %>
      </div>
    <% end %>
    
    <%= link_to 'Back to Posts', posts_path, class: 'btn btn-primary' %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-4">
  <h1 class="text-center">All Posts</h1>

  <div class="d-flex justify-content-center">
    <a href="<%= new_post_path %>" class="btn btn-primary mt-5 mb-5">New Post</a>
  </div>
  
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4 col-sm-6 col-12 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 calss="card-title"><%= post.title %></h5>
            <p class="card-text"><small class="text-muted">Posted by: <%= post.user.email %></small></p>
            <p>Date: <%= post.created_at.strftime("%B %d, %Y") %></p>
            <a href="<%= post_path(post) %>" class="btn btn-primary">Show This Post</a>
            <a href="<%= new_post_path %>" class="btn btn-primary">New Post</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="card new-post my-5">
  <div class="card-body">
  <h1 class="new-post-title text-center">New Post</h1>
  <%= form_with(model: @post, local: true) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control", placeholder: "Enter post title" %>
    </div>
  
    <div class="mb-3">
      <%= form.label :body, class: "form-label" %>
      <%= form.text_area :body, class: "form-control", placeholder: "Enter post content" %>
    </div>
  
    <div class="text-center">
      <%= form.submit %>
    </div>
  <% end %> 
  <%= link_to 'Back to Posts', posts_path, class: 'btn btn-primary' %> 
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-4">
  <h1><%= @post.title %></h1>
  <p class="text-muted">
    Posted by <%= @post.user.email %> on <%= @post.created_at.strftime("%B %d, %Y") %>
  </p>
  <p><%= @post.body %></p>
  
      <h2>Comments</h2>
  
      <% @comments.each do |comment| %>
       <div class="card mb-3">
          <div class="card-body">
          <p><%= comment.body %> - <small class="text-muted">Posted by <%= comment.user.email %></small></p>
            <div class="button-group">
              <%= link_to 'Edit Comment', edit_comment_path(comment), class: "btn btn-warning btn-sm" %> |
              <%= link_to 'Reply', new_comment_path(post_id: @post.id, parent_id: comment.id), class: "btn btn-info btn-sm" %> |
              <%= button_to 'Delete Comment', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
            </div>
          </div>
          <div class="card-footer">
            <% comment.replies.each do |reply| %>
              <div class="border p-2 mb-2" style="margin-left: 20px; background-color: #f8f9fa;">
                <p><%= reply.body %> - <small class="text-muted">Posted by <%= reply.user.email %></small></p>
                <div class="button-group">
                  <%= link_to 'Edit Reply', edit_comment_path(reply), class: "btn btn-warning btn-sm" %> |
                  <%= button_to 'Delete Reply', comment_path(reply), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                </div>
              </div>
            <% end %>
          </div>
       </div>
      <% end %>
    <div class="d-flex flex-wrap mb-3">
     <div>
      <%= link_to 'Add Comment', new_comment_path(post_id: @post.id), class: 'btn btn-primary' %>
      <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
      <%= link_to 'Update Post', edit_post_path(@post), class: 'btn btn-primary' %>
      <%= link_to 'Back to Posts', posts_path, class: 'btn btn-primary' %>
      <%= button_to 'Delete Post', post_path(@post), method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this post?' }, class: "btn btn-danger" %>
     </div>
    </div>
</div>
  